# @format

version: "3.8"

services:
    user-service:
        build:
            context: ./user-service
        ports:
            - "8083:8083"
        volumes:
            - ./user-service:/app
        environment:
            - DB_HOST=host.docker.internal
            - DB_USER=default
            - DB_PASSWORD=secret
            - DB_NAME=go-microservices
        depends_on:
            - rabbitmq # Your other dependencies, if any
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"
