# @format

version: "3.8"

services:
    user-service:
        build:
            context: ./user-service
        ports:
            - "8083:8083"
        volumes:
            - ./user-service:/app
        environment:
            - DB_HOST=host.docker.internal
            - DB_USER=default
            - DB_PASSWORD=secret
            - DB_NAME=go-microservices
        depends_on:
            rabbitmq:
                condition: service_healthy
        restart: always

    order-service:
        build:
            context: ./order-service
        ports:
            - "8084:8084"
        volumes:
            - ./order-service:/app
        environment:
            - DB_HOST=host.docker.internal
            - DB_USER=default
            - DB_PASSWORD=secret
            - DB_NAME=go-microservices
        depends_on:
            rabbitmq:
                condition: service_healthy
        restart: always

    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 10s
            retries: 5
        restart: always
